use std::{env, fs, path::PathBuf};

const DEFAULTS: &[(&str, &str, &str)] = &[
    ("MAX_SEARCH_DEPTH", "u8", "64"),
    ("PVS_FULL_WINDOW_MOVES", "usize", "2"),
    ("MOVE_PICKER_CAPTURE_BASE", "i32", "10000"),
    ("MOVE_PICKER_PROMOTION_BASE", "i32", "20000"),
    ("QSEARCH_DELTA_MARGIN", "i32", "200"),
    ("QSEARCH_CAPTURE_BASE", "i32", "10000"),
    ("QSEARCH_PROMOTION_BASE", "i32", "20000"),
];

fn main() {
    let mut output = String::from("// @generated by crates/search/build.rs\n");
    for &(name, ty, default) in DEFAULTS {
        let env_name = format!("OOPSMATE_{name}");
        println!("cargo:rerun-if-env-changed={env_name}");
        let value = env::var(&env_name).unwrap_or_else(|_| default.to_owned());
        validate_int(&env_name, &value, ty);
        output.push_str("pub(crate) const ");
        output.push_str(name);
        output.push_str(": ");
        output.push_str(ty);
        output.push_str(" = ");
        output.push_str(&value);
        output.push_str(";\n");
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR missing"));
    fs::write(out_dir.join("tune.rs"), output).expect("write generated tune.rs");
}

fn validate_int(name: &str, value: &str, ty: &str) {
    match ty {
        "u8" => {
            value.parse::<u8>().unwrap_or_else(|_| panic!("{name} must be a u8, got {value:?}"));
        }
        "usize" => {
            value
                .parse::<usize>()
                .unwrap_or_else(|_| panic!("{name} must be a usize, got {value:?}"));
        }
        "i16" => {
            value
                .parse::<i16>()
                .unwrap_or_else(|_| panic!("{name} must be an i16, got {value:?}"));
        }
        "i32" => {
            value
                .parse::<i32>()
                .unwrap_or_else(|_| panic!("{name} must be an i32, got {value:?}"));
        }
        _ => unreachable!(),
    }
}
