use std::{env, fs, path::PathBuf};

const DEFAULTS: &[(&str, &str, &str)] = &[
    ("MAX_SEARCH_DEPTH", "u8", "64"),
    ("PVS_FULL_WINDOW_MOVES", "usize", "2"),
    ("ASPIRATION_MIN_DEPTH", "u8", "5"),
    ("ASPIRATION_WINDOW", "i32", "150"),
    ("ASPIRATION_MAX_WINDOW", "i32", "1000"),
    ("NULL_MOVE_MIN_DEPTH", "u8", "4"),
    ("FUTILITY_MAX_DEPTH", "u8", "7"),
    ("RFP_MAX_DEPTH", "u8", "7"),
    ("RFP_MARGIN_1", "i32", "125"),
    ("RFP_MARGIN_2", "i32", "250"),
    ("RFP_MARGIN_3", "i32", "375"),
    ("RFP_MARGIN_4", "i32", "500"),
    ("RFP_MARGIN_5", "i32", "625"),
    ("RFP_MARGIN_6", "i32", "750"),
    ("RFP_MARGIN_7", "i32", "875"),
    ("RAZOR_MAX_DEPTH", "u8", "2"),
    ("RAZOR_MARGIN_1", "i32", "400"),
    ("RAZOR_MARGIN_2", "i32", "500"),
    ("RAZOR_MARGIN_3", "i32", "600"),
    ("FUTILITY_MARGIN_1", "i32", "90"),
    ("FUTILITY_MARGIN_2", "i32", "180"),
    ("FUTILITY_MARGIN_3", "i32", "270"),
    ("FUTILITY_MARGIN_4", "i32", "360"),
    ("FUTILITY_MARGIN_5", "i32", "450"),
    ("FUTILITY_MARGIN_6", "i32", "540"),
    ("FUTILITY_MARGIN_7", "i32", "630"),
    ("LATE_QUIET_PRUNE_MIN_DEPTH", "u8", "3"),
    ("LATE_QUIET_PRUNE_MAX_DEPTH", "u8", "6"),
    ("LATE_QUIET_PRUNE_MOVE_MULT", "usize", "8"),
    ("LATE_QUIET_PRUNE_MOVE_OFFSET", "usize", "6"),
    ("LMR_MIN_DEPTH", "u8", "3"),
    ("LMR_FULL_DEPTH_MOVES", "usize", "3"),
    ("MOVE_PICKER_CAPTURE_BASE", "i32", "10000"),
    ("MOVE_PICKER_BAD_CAPTURE_BASE", "i32", "0"),
    ("MOVE_PICKER_PROMOTION_BASE", "i32", "20000"),
    ("QSEARCH_DELTA_MARGIN", "i32", "200"),
    ("QSEARCH_CAPTURE_BASE", "i32", "10000"),
    ("QSEARCH_PROMOTION_BASE", "i32", "20000"),
];

fn main() {
    let mut output = String::from("// @generated by crates/search/build.rs\n");
    for &(name, ty, default) in DEFAULTS {
        let env_name = format!("OOPSMATE_{name}");
        println!("cargo:rerun-if-env-changed={env_name}");
        let value = env::var(&env_name).unwrap_or_else(|_| default.to_owned());
        validate_int(&env_name, &value, ty);
        output.push_str("pub(crate) const ");
        output.push_str(name);
        output.push_str(": ");
        output.push_str(ty);
        output.push_str(" = ");
        output.push_str(&value);
        output.push_str(";\n");
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR missing"));
    fs::write(out_dir.join("tune.rs"), output).expect("write generated tune.rs");
}

fn validate_int(name: &str, value: &str, ty: &str) {
    match ty {
        "u8" => {
            value
                .parse::<u8>()
                .unwrap_or_else(|_| panic!("{name} must be a u8, got {value:?}"));
        }
        "usize" => {
            value
                .parse::<usize>()
                .unwrap_or_else(|_| panic!("{name} must be a usize, got {value:?}"));
        }
        "i16" => {
            value
                .parse::<i16>()
                .unwrap_or_else(|_| panic!("{name} must be an i16, got {value:?}"));
        }
        "i32" => {
            value
                .parse::<i32>()
                .unwrap_or_else(|_| panic!("{name} must be an i32, got {value:?}"));
        }
        _ => unreachable!(),
    }
}
